### ISSUE TITLE
Make layers way less transparent as default.

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/regional-equity-atlas#4]
Transparent overlays are a little disorienting for people with less exposure to web-mapping.

Default transparency should definitely be bumped up (currently at 0.5) but we should explore other stylistic changes to support this.

@jtutak Have you seen any hatching options in MapBox? That could allow for fully opaque layers look right, overlap, and not disagree with the legends.

**Comment by jtutak** [comment]
I haven't seen that, but it could exist.
